# Generated by Django 5.1 on 2024-08-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(default='player1', max_length=255)),
                ('player2', models.CharField(default='player2', max_length=255)),
                ('player3', models.CharField(default='player3', max_length=255)),
                ('player4', models.CharField(default='player4', max_length=255)),
            ],
        ),
    ]
