# Generated by Django 5.1 on 2024-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='clients_connected',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='play',
            name='nb_players',
            field=models.IntegerField(choices=[(2, 'Deux joueurs'), (4, 'Quatre joueurs')], default=2),
        ),
        migrations.AddField(
            model_name='play',
            name='player_connected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='play',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
