# Generated by Django 5.1 on 2024-09-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_play_clients_connected_play_nb_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='clients_connected',
        ),
    ]
